services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # port
      - "15672:15672" # management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
volumes:
  rabbitmq_data:
